project:
  type: website

execute:
  freeze: auto

filters:
  - timeline

website:
  title: "quarto-timeline"
  navbar:
    left:
      - text: "Get Started"
        href: index.qmd
      - text: "Gallery"
        href: gallery.qmd
      - text: "Documentation"
        menu:
          - text: "Layouts"
            href: layouts.qmd
          - text: "Fragments"
            href: fragments.qmd
          - text: "Images & Plots"
            href: images.qmd
          - text: "Programmatic"
            href: programmatic.qmd
          - text: "Customization"
            href: customization.qmd
          - text: "Theming"
            href: theming.qmd
    right:
      - icon: github
        href: https://github.com/EmilHvitfeldt/quarto-timeline
        aria-label: GitHub

format:
  html:
    toc: true
    toc-depth: 2
    css: styles.css
