project:
  type: website

filters:
  - timeline

website:
  title: "quarto-timeline"
  navbar:
    left:
      - text: "Get Started"
        href: index.qmd
      - text: "Layouts"
        href: layouts.qmd
      - text: "Fragments"
        href: fragments.qmd
      - text: "Images & Plots"
        href: images.qmd
      - text: "Programmatic"
        href: programmatic.qmd
      - text: "Customization"
        href: customization.qmd
      - text: "Gallery"
        href: gallery.qmd

format:
  html:
    toc: true
    toc-depth: 2
